### ISSUE TITLE
Questions About Setup and Script Usage

### ISSUE THREAD

**Issue by jwakre** [srwalter/jenkins-yocto-tools#1]
I am working on setting up my team's CI system and was pointed to this repo by Randy Witt. I am also using Jenkins with Yocto Project and found these scripts a good starting place for building images and capturing logs. I have been trying to think about the best way to use these scripts. So far, I have been planning on adding them to a Jenkinsfile and wrapping the call to bitbake with a container like [crops/yocto-dockerfiles](https://github.com/crops/yocto-dockerfiles).

I heard you were doing something useful with containers in your CI implementation. Could you share more insight into your CI setup or additional scripts/Dockerfiles?

Thanks,
John

**Comment by srwalter** [comment]
Hi John!
Always happy to help fellow bitbake users.  I just added the scripts we use for docker integration to this repo.  The idea is that you can modify yocto-build (or any other place that runs bitbake) and run the docker-bitbake script instead, and have that work seamlessly.  Like with the existing scripts, they assume that jenkins-yocto-tools is checked out right next to poky, possibly as git submodules of a supermodule.  Take a look, and if you have any questions feel free to ask!
